### PR TITLE
Added node.js documentation

### PR DESCRIPTION
**Pull request by benh-gds**

### CODE REVIEW

**Comment by combor** [comment]
I think we can improve commit messages a bit as we also use them as documentation. Please take a look here: https://government-paas-team-manual.readthedocs.io/en/latest/team/working_practices/#commit-messages

**Comment by Jonty** [comment]
@benh-gds We should squash these three commits into one before merging them - are you comfortable using git rebase to do that, or would you like help?

**Comment by benh-gds** [comment]
I don't know how to use git rebase at all so would appreciate some help!

**Comment by Jonty** [comment]
Other than that it looks great! Let me know if you'd like me to roll over and help with the commit squashing.

**Pull request merged**
