### PR TITLE
[#134505325] Add password guidance to getting started docs

### PR DESCRIPTION
**Pull request by Jonty**
## What

Adds guidance on choosing good passwords and how to manage them.

## How to review

Check it makes sense.

## Who can review

Not @jonty, because he is on holiday 🎄.

### CODE REVIEW

**Comment by mtekel** [comment]
Lg. But I'm not sure if to open flame about online password managers (which are so lucrative target of hacks) or not.

**Comment by keymon** [comment]
It LGTM, but I had to add an additional commit to add the page to `mkdocs.yml`. 

I am OK with the recommendation of online password managers.

Said that, this PR has 2x :+1:, but as I added one commit I should merge? Maybe @mtekel can do the honours.

**Comment by benh-gds** [comment]
Can I just check this over for style before we merge?

**Comment by keymon** [comment]
@benh-gds be my guest! :smile:

**Comment by Jonty** [comment]
LGTM, thanks for the catch @keymon 👍

**Comment by keymon** [comment]
@benh-gds has added some additional changes. I squashed all the changes and I will merge now.

**Pull request merged**
